feat: add Binance support
Adamant-im/adamant-coinoptimus pull request #1
Opened 2023-04-05 14:40 UTC by adamant-al

- Add Binance Support
- Resolve a minor bug with Ladder
- Remove default p2pb2b trade config
- Add optional `loadMarket` param to exchange's API initialization

2023-04-07 11:21 UTC, martiliones requested changes

2023-04-07 11:21 UTC, martiliones commented on trade/trader_binance.js
> +      } else {
Unnecessary `else`

2023-04-07 11:21 UTC, martiliones commented on trade/trader_binance.js
> +            data.balances.forEach((crypto) => {
use `map`
```js
let result = data.balances.map((crypto) => ({
  code: crypto.asset,
  free: +crypto.free,
  freezed: +crypto.locked,
  total: +crypto.free + +crypto.locked,
}));
```

2023-04-07 11:21 UTC, martiliones commented on trade/trader_binance.js
> +      const pair_ = formatPairName(pair);
confusing variable name

2023-04-07 11:21 UTC, martiliones commented on trade/trader_binance.js
> +        binanceApiClient.cancelAllOrders(pair_.pairPlain).then(function(data) {
use arrow function as you did below

2023-04-07 11:21 UTC, martiliones commented on trade/trader_binance.js
> +            result.asks.sort(function(a, b) {
use arrow function

2023-04-07 11:33 UTC, martiliones commented
I think we should change the structure of the project to be more clear until we have implemented many more exchanges.

From that:

```
.
└── trade
    ├── api
    │   ├── bar_api.js
    │   └── foo_api.js
    ├── settings
    │   ├── tradeParams_bar.js
    │   └── tradeParams_foo.js
    ├── trader_bar.js
    └── trader_foo.js
```

to something like this:

```
.
└── trade
    ├── bar
    │   ├── api.js
    │   ├── index.js
    │   └── settings.js
    ├── foo
    │   ├── api.js
    │   ├── index.js
    │   └── settings.js
    └── shared.js
```

Thus, it should be easier to work on a single exchange and to access shared files, such as utilities

2023-04-07 11:59 UTC, adamant-al commented
@martiliones Make a PR to `feature/binance` covering these changes.

2023-04-10 03:52 UTC, adamant-al commented on trade/trader_binance.js
> +      try {
For `async` implementation, don't use nested `try-catch`.
See `getOrderDetails()` as a sample.

2023-04-10 03:52 UTC, adamant-al commented on trade/trader_binance.js
> +      } catch (error) {
If you change `catch (err)` ⟶ `catch (error)`, change it everywhere in the module.
Same for `catch (e)`.

2023-04-10 03:52 UTC, adamant-al commented on trade/api/binance_api.js
> +          const unexpectedErrorCode = data && (error.code >= -1100 || error.code <= -2013) ?
`error.code > -1100 || error.code < -2013`

2023-04-10 03:52 UTC, adamant-al commented on trade/api/binance_api.js
>          timeout: 10000,
Try set `timeout: 1` and run `/balances` command.

Expected:
`Request to https://api.binance.com/api/v3/account with data timestamp=1681096444784&signature=49e893465635be06e99058ff6991e97fb421a23ddeaa1d53c5ff1f3ccc48bd89 failed. Unknown error: AxiosError: timeout of 1ms exceeded. Rejecting…`

In fact: `Error while processing response of request to https://api.binance.com/api/v3/account with data timestamp=1681097715028&signature=e076850fa6286e0c5c523700ad34dc1dd2fbcb4e34bc9f7812c9ebaec755c47a: TypeError: Cannot set properties of undefined (setting 'binanceErrorInfo'). Data object I've got: undefined.`

2023-04-11 04:03 UTC, adamant-al commented
@martiliones Good work.
Approve the PR.

2023-04-13 13:58 UTC, joebrock666 reviewed
I would suggest to add new lines in the end of the files

2023-04-13 15:35 UTC, joebrock666 approved these changes

2023-04-14 01:07 UTC, Andrey1029 approved these changes

2023-04-14 02:50 UTC, merged